language: go
go:
- 1.5
- tip
deploy:
  provider: heroku
  api_key:
    secure: nhvshJJAMygw/TAxIvsSCzTDnKdXuzEShpHHYFdQFMITy/KVQlRoJuR1Q/WrC7keE15iT2pUOl6pNqjTgN8YqmmenztFfDmSnU8HAwtQ78TLUDL4afUFANouFTIQTvJMKdRJvK8KVDxe2M8dMSGRbPeCKBgephlS4D1KvvYi8koYtfqzjdFAiP46zR+p7OBN/SAijbe7/iDv6Rp2y1DWL+R6BE2M44yKn6ojYaWZpWbVxWaEQCABC7eWk2ythcKkZJuwQDVkogh4DV71rkK5yKsCBFUlpJjsWOAafyZIBPaw8GQB8R8E1XYdTUwypsKNmyBz8KgGgcK3ialSdFMGU6MYUxDE3VcLzDCdbC8dLfo8KI79p0TY9TBZLPyEJfPIidwh9zpZ9x1K4abdUaknJt8sFBEV1UkNJAEvAMEyE4Bbo93CatdF15SmNhUCNSsyu+WKkBhNRpcIzy53aj0tZjsJy/2erWlOxfEihK84q5pujLS7G3XMYskjeUtIKsXJ/RASiqvLIK+uBKkBG1CLVqEFbWUBkgEO6cNFaVIV5bZRDB21syoBCfCLbrcPIWRqWEXHDfWBU24JcIV7BC5nEGtuaciA+UCWFcskB90nf/1nF+UbKAblw7DXIClRnvR91AzmEeIKENOEzYAdULbE35qHZE2tpUr1adAJzETbPOQ=
  app: ke-unitrack
